/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Header from './Header/Header'
import MainContent from './MainContent/MainContent'

const App: React.FC = () => {
	return (
		<div className="flex overflow-hidden flex-col pb-4  ">
			<Header />
			<MainContent />
		</div>
	)
}

export default App
