/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const AuthButtons: React.FC = () => {
	return (
		<div className="flex gap-4 items-center self-stretch text-sm font-medium leading-snug text-white">
			<button className="self-stretch my-auto">Sign In</button>
			<button className="gap-2 self-stretch px-4 py-2 my-auto rounded-lg">
				Join Now
			</button>
		</div>
	)
}

export default AuthButtons
