/**
 * This code was generated by Builder.io.
 */
import { GitHubLogoIcon } from '@radix-ui/react-icons'
import Link from 'next/link'
import React from 'react'

const AuthButtons: React.FC = () => {
	return (
		<div className="flex gap-4 items-center self-stretch text-sm font-medium leading-snug text-white">
			<Link
				href="https://github.com/remcostoeten/nextjs15-toploader-page-transition-no-libraries"
				target="_blank"
				className="gap-2 self-stretch px-4 py-2 my-auto rounded-lg"
			>
				<GitHubLogoIcon className="w-4 h-4" />
			</Link>
		</div>
	)
}

export default AuthButtons
