/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const Logo: React.FC = () => {
	return (
		<div className="flex gap-2 items-center self-stretch my-auto">
			<img
				loading="lazy"
				src="https://cdn.builder.io/api/v1/image/assets/TEMP/fa5a567a6f6d1e9f39e8491b1557d4f29876fed681a01ae6f5d1b344b1907261?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
				alt=""
				className="object-contain shrink-0 self-stretch my-auto w-6 aspect-[0.86]"
			/>
			<img
				loading="lazy"
				src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ac87be885f3745e7e4dad1624652ecabd4d576138a5500c99a56a86ff8050c4?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
				alt=""
				className="object-contain shrink-0 self-stretch my-auto aspect-[1.32] w-[29px]"
			/>
		</div>
	)
}

export default Logo
