/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const MENU_ITEMS = [
	{ label: 'Home', href: '/' },
	{ label: 'Normal speed route', href: '/normal' },
	{ label: 'Slow route', href: '/slow' },
	{ label: 'Suuuuuper slow route', href: '/super-slow' }
]

const Navigation: React.FC = () => {
	return (
		<nav className="flex gap-6 justify-center items-center self-stretch my-auto text-sm font-medium leading-snug text-white whitespace-nowrap">
			{MENU_ITEMS.map(item => (
				<a
					key={item.label}
					href={item.href}
					className="self-stretch my-auto"
				>
					{item.label}
				</a>
			))}
		</nav>
	)
}

export default Navigation
